apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-http-deployment
spec:
  replicas: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-http-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Disable SSL redirect for local development
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  # No TLS for local development
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: golang-http-service
            port:
              number: 80 