apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-http-docker-desktop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Leakageonthelamp/argocd-config
    path: overlays/docker-desktop
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: playground
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true