apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-http-deployment
spec:
  replicas: 3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-http-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"  # If using cert-manager
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - prod.localhost  # For Docker Desktop testing
    secretName: golang-http-tls
  rules:
  - host: prod.localhost  # For Docker Desktop testing
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: golang-http-service
            port:
              number: 80 