apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-http-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-http
  template:
    metadata:
      labels:
        app: golang-http
    spec:
      containers:
      - name: golang-http
        image: lookkrit/golang-http:v1
        ports:
        - containerPort: 3000
        env:
        - name: APP_PORT
          value: "3000"