apiVersion: v1
kind: Service
metadata:
  name: golang-http-service
spec:
  type: NodePort
  selector:
    app: golang-http
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-http-ingress
$patch: delete 